name: pollywallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+2

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  web3dart: ^2.0.0-dev.9
  flutter_string_encryption: ^0.3.1
  http: ^0.12.2
  hex: ^0.1.2
  bip39: ^1.0.3
  bip32: any
  fluttertoast: ^7.1.6
  flutter_spinkit: "^4.1.2"
  qr_flutter: ^3.2.0
  numeric_keyboard: ^1.0.0
  pinput: ^0.2.6
  flutter_bloc: ^6.1.1
  bloc: ^6.1.1
  barcode_scan: ^3.0.1
  build_runner: ^1.10.12
  hive_generator: ^0.8.2
  slide_to_confirm: ^0.0.7
  share: ^0.6.5+4
  flutter_countdown_timer: ^3.0.0
  url_launcher: ^5.7.10
  flutter_webview_plugin: ^0.3.11
  flutter_svg: any

  # you may delete the below ones
  # googleapis: ^0.54.0
  # googleapis_auth: ^0.2.11
  # google_sign_in: ^4.1.0
  # firebase_auth: ^0.15.2
  # path_provider: ^1.5.1
  # file_picker: ^1.3.8
  # flutter_secure_storage: ^3.3.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/qr_icon.png
    - assets/icons/wallet_icon.png
    - assets/icons/settings_icon.png
    - assets/icons/staking_icon.png
    - assets/icons/transfer_icon.png
    - assets/icons/token_icon.png
    - assets/abi/childERC20.json
    - assets/abi/deposit_manager.json
    - assets/abi/erc20.json
    - assets/abi/erc20predicate.json
    - assets/abi/erc721.json
    - assets/abi/plasma_registry.json
    - assets/abi/root_chain_proxy.json
    - assets/abi/root_chain.json
    - assets/abi/withdraw_manager.json
    - assets/icons/profit.png
    - assets/abi/staking_contract.json
    - assets/icons/image_not_found.png
    - assets/abi/erc1155.json
    - assets/abi/mrc20.json
    - assets/abi/childERC721.json
    - assets/abi/childERC1155.json

    # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
